version: '3.6'

services:
  mc:
    image: memcached
    ports:
      - "11211:11211"
    network_mode: 'host'
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - 80:80
      # - 443:443
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
  # adminer:
  #   image: adminer
  #   ports:
  #     - "18080:18080"
  #   network_mode: 'host'
  # nginx:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - "./nginx.conf:/etc/nginx/nginx.conf"
  #   command: [nginx-debug, '-g', 'daemon off;']
  #   network_mode: 'host'
  # webpack:
  #   image: "node:8-slim"
  #   user: "node"
  #   working_dir: /home/node/app
  #   environment:
  #     - DEVELOPMENT=TRUE
  #   volumes:
  #     - /home/hekar/code/codetalks-web:/home/node/app
  #   expose:
  #     - "5001"
  #   ports:
  #     - "5001:5001"
  #   command: "npm start"
  #   network_mode: 'host'
  # codetalks:
  #   image: "node:8-slim"
  #   user: "node"
  #   working_dir: /home/node/app
  #   depends_on:
  #     - "db"
  #     - "mc"
  #   volumes:
  #     - /home/hekar/code/codetalks-node:/home/node/app
  #   expose:
  #     - "5002"
  #   ports:
  #     - "5002:5002"
  #   command: "npm start"
  #   network_mode: 'host'
