version: '3.6'

services:
  mc:
    image: memcached
    ports:
      - "11211:11211"
    network_mode: 'host'
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
